pws/BRM/urls.py
from django.urls import path
from BRM import views

urlpatterns=[
    path('login/',views.login),
    path('logout/',views.logout),
    path('profile/',views.profile),
]

pws/pws/urls.py
from django.contrib import admin
from django.urls import path,include
from posts.admin import admin_site


urlpatterns = [
   # path('admin/', admin.site.urls), with the default settings
   path('admin/',admin_site.urls),
    path('pages/',include('pages.urls')),
    #path('posts/',include('posts.urls')),
    path('user/',include('user.urls')),
    path('BRM/',include('BRM.urls')),
    path('classBase/',include('classBase.urls')),
    path('api/',include('api.urls')),   
]

pws/posts/models.py
from django.db import models
from django import forms
from django.core import validators
from django.core.validators import ValidationError
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import format_html

class Category(models.Model):
    title=models.CharField( max_length=250)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title 
    def natural_key(self):
        return [self.id , self.title]
        

    class Meta:
        db_table="categories"
        verbose_name="Category"
        verbose_name_plural="Categories"
    

STATUS_CHOICES = [
    ('d', 'Draft'),
    ('p', 'Published'),
    ('w', 'Withdrawn'),
]

class Posts(models.Model):  
    
    title=models.CharField( max_length=250)
    content=models.TextField()
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    thumbnail=models.FileField(upload_to="posts/",null=True)
    category=models.ManyToManyField(Category,related_name="categories")
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects=models.manager
    status=models.CharField(max_length=1,choices=STATUS_CHOICES,default="d")
    
    def get_absolute_url(self):
        return reverse("post-detail",kwargs={"pk":self.pk})

    def __str__(self):
        return self.title
    

    __str__.short_description="Post Title"
    
    def show_thumbnail(self):
        return format_html('<img src="/static/%s" width="100" height="75" />'%self.thumbnail)
    def show_content(self):
        return format_html(self.content)
    show_content.short_description="Post Content"
    class Meta:
        db_table="posts"
        verbose_name="Post"
        verbose_name_plural="Posts"
    


class PostsForm(forms.ModelForm):
    class Meta:
        model=Posts
        fields=['title','content','thumbnail','user','category']
        widgets={
            "title":forms.TextInput(attrs={"class":"form-control","placeholder":"Enter post title length should be >10"}),
            "content":forms.Textarea(attrs={"class":"form-control"}),
            "user":forms.Select(attrs={"class":"forms-control"}),
            "category":forms.CheckboxSelectMultiple(attrs={"class":"forms-control"}),
            "thumbnail":forms.ClearableFileInput(attrs={'multiple': True}),
        }
    def clean(self):
        fields=self.cleaned_data
        keys=list(fields.keys())
        if(len(fields[keys[0]])<10):
            raise ValidationError(f"{keys[0]} have less then 10 valuse ")
        if(len(fields[keys[1]])<10):
            raise ValidationError(f"{keys[1]} have less then 10 valuse")

    
class Gallery(models.Model):
    post=models.ForeignKey(Posts,on_delete=models.CASCADE)
    images=models.FileField(upload_to="posts/",blank=True,null=True)
    def __str__(self):
        return self.post.title
    class Meta:
        verbose_name="Gallery"
        verbose_name_plural="Galleries"

    

pws/posts/views.py
from posts.models import Posts,PostsForm,Category,Gallery
from django.views.generic.edit import FormView,CreateView,UpdateView,DeleteView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.http import HttpResponse

from django.core.mail import send_mail,send_mass_mail,mail_admins,mail_managers


class index(FormView):
    template_name="cindex.html"
    form_class=PostsForm
    success_url="/"

class Post_Detail(DetailView):
    model=Posts

class show(TemplateView):
    template_name="posts/list_posts.html"
    model=Posts
    success_url="/"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Posts.objects.all()#context_object_name="post"
        return context

class add(CreateView):
    model=Posts
    fields="__all__"
    



class edit(UpdateView):
    model=Posts
    fields="__all__"
    success_url="/posts/"


class delete(DeleteView):
    model=Posts
    success_url=reverse_lazy('show')

def mail(request):
    mail1=send_mail("New Year","Hell good wishes from the Ravi","chananias1@gmail.com",["vjy@gmail.com",],fail_silently=False,html_message="Hello Text here")
    if mail1:
        return HttpResponse(mail1)
    else:
        raise Exception("Error occuree")
def massmail(request):
    mail1=("New Year","Hell good wishes from the Ravi","chananias1@gmail.com",["vjy@gmail.com",])
    mail2=("New Year","Hell good wishes from the Vijay","chananias1@gmail.com",["vjy@gmail.com",])
    mail=send_mass_mail((mail1,mail2),fail_silently=False)
    if mail:
        return HttpResponse(mail)
    else:
        raise Exception("Error Ocuuce in mass mail")
    
def mail_admin(request):
    mail_admins("BUGS","hello admin we found many error in website",fail_silently=False)
    return  HttpResponse("Email send successfully")

def mail_manager(request):
    mail_managers("Manager List","We are lisiting the time for all the manager",fail_silently=False)
    return HttpResponse("Email send to Manager")

pws/posts/templates/posts/Posts_Detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Inside detail View</h1>
    <p>{{object.title}}</p>
    <p>{{object.content}}</p>
  

</body>
</html>

pws/posts/templates/posts/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

</head>
<body>
    {% block content %} {% endblock %}
    
</body>
</html>

pws/posts/templates/posts/list_posts.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="container">
    <a href="/posts/add/">Add Post</a>

    <div class="data form-row">

        {% for r in object_list %}
        <p>{{r.title}}</p>
        <a href="{% url 'post-edit' r.id %}" >Edit post</a><br>
        <a href="{% url 'post-delete' r.id %}"> Delete Post</a><br>

        <a href="{% url 'post-detail' r.id %}">View Detail</a>
        <p> {{r.content}}</p>
        <p>{{r.created_at}}</p>
        <p>{{r.user.username}}</p>
        <p><img src="{% static r.thumbnail.url %}" width="250" height="150"></p>
        <p>
            <h1 >Gallery Image </h1>
        </p>
        {% for gallery in r.gallery_set.all %}

        <img src="{% static gallery.images.url %}" />

        {% endfor %}
        {% endfor %}
    </div>
    
    <div class="form-row">
        <h1>Categories </h1>
        {% for cat in categories %}
        {{cat.title| join:" "}}
        {% endfor %}
    </div>
</div>

{% endblock %}

pws/posts/templates/posts/posts_confirm_delete.html
{% extends 'layout.html' %}
{% load static %}
{% block content %} 
<div class="container ">
    <form action="" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
      <p class="text-primary">Are you Want to delete {{object.title}}</p>   
    <button type="submit" class="btn-outline-danger" >yes Delete</button>
    <a href="{% url 'post-detail' object.id %}">Cancle</a>
    
    </form>
    </div>
  
{% endblock %}

pws/posts/templates/posts/posts_form.html
{% extends 'layout.html' %}
{% load static %}
{% block content %} 
<div class="container">
    <form action="" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
        {% if form.title.errors %}
        {{form.title.errors}}
        {% endif %}
        {% if form.non_field_errors %}
        {% for r in form.non_field_errors %}
        {{r}}
        {% endfor %}
        {% endif %}     
        <div class="form-row">
            {% csrf_token %}
            {% for f in form %}
            {{ f.label_tag }}
            <p>{{f}}</p>
            {% endfor %}   
        </div>
    <input type="submit" value="Submit">
    </form>
  
{% endblock %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>